# Same as examples/app_share_pos/Makefile in the CrazyThymio-firmware fork: copy this whole
# directory into that fork's examples/ folder, then `make clean && make -j && make cload`.
CRAZYFLIE_BASE := ../..
OOT_CONFIG := $(PWD)/app-config
include $(CRAZYFLIE_BASE)/tools/make/oot.mk
